# Generated by Django 5.2.8 on 2025-11-06 01:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='セッションID')),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('completed', '完了'), ('abandoned', '中断')], default='in_progress', max_length=20, verbose_name='ステータス')),
                ('applicant_data', models.JSONField(default=dict, verbose_name='申請者情報')),
                ('diagnosis_result', models.JSONField(blank=True, default=dict, verbose_name='診断結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '診断セッション',
                'verbose_name_plural': '診断セッション一覧',
                'db_table': 'diagnosis_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='資格コード')),
                ('name_ja', models.CharField(max_length=100, verbose_name='資格名（日本語）')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='資格名（英語）')),
                ('category_type', models.CharField(choices=[('work', '就労'), ('activity', '身分・地位'), ('specified', '特定活動')], max_length=20, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('priority', models.IntegerField(default=0, verbose_name='優先順位')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '在留資格',
                'verbose_name_plural': '在留資格一覧',
                'db_table': 'visa_categories',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IndustryVisaMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100, verbose_name='業種')),
                ('job_category', models.CharField(max_length=100, verbose_name='職種')),
                ('match_score', models.IntegerField(help_text='0-100の範囲で適合度を入力', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='適合度')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('visa_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_mappings', to='visa_diagnosis.visacategory', verbose_name='在留資格')),
            ],
            options={
                'verbose_name': '業種職種マッピング',
                'verbose_name_plural': '業種職種マッピング一覧',
                'db_table': 'industry_visa_mapping',
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, verbose_name='書類名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='必須')),
                ('url', models.URLField(blank=True, verbose_name='参考URL')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('visa_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visa_diagnosis.visacategory', verbose_name='在留資格')),
            ],
            options={
                'verbose_name': '必要書類テンプレート',
                'verbose_name_plural': '必要書類テンプレート一覧',
                'db_table': 'document_templates',
                'ordering': ['visa_category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('education', '学歴'), ('experience', '実務経験'), ('qualification', '資格'), ('salary', '報酬'), ('company', '企業要件'), ('other', 'その他')], max_length=30, verbose_name='要件種別')),
                ('condition', models.TextField(verbose_name='要件内容')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='必須')),
                ('alternative_condition', models.TextField(blank=True, verbose_name='代替条件')),
                ('alternative_ok', models.BooleanField(default=False, verbose_name='代替可能')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('visa_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='visa_diagnosis.visacategory', verbose_name='在留資格')),
            ],
            options={
                'verbose_name': '在留資格要件',
                'verbose_name_plural': '在留資格要件一覧',
                'db_table': 'visa_requirements',
                'ordering': ['visa_category', 'display_order', 'requirement_type'],
            },
        ),
    ]
